inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SignalException:
  Enabled: false

# Allow: task foo: [:bar, :baz]
Style/SymbolArray:
  Enabled: false

Style/LeadingCommentSpace:
  Exclude:
    - Gemfile  # RVM doesn't recognise spaces after the #s
